scan_filter_chain:
- name: shadows
  type: laser_filters/ScanShadowsFilter
  params:
    min_angle: 5
    max_angle: 175
    neighbors: 5
    window: 1
- name: too_close
  type: laser_filters/LaserScanRangeFilter
  params: 
    lower_threshold: 0.4
    upper_threshold: .inf
